In [43]:
import numpy as np

In [44]:
myArray = np.arange(0,15)

In [45]:
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
myArray[5]


5

In [47]:
myArray[3:8]

array([3, 4, 5, 6, 7])

stop index dahil değil

In [48]:
myArray[3:8] = -5

In [49]:
myArray

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [50]:
array2 = np.arange(0,24)

In [51]:
array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [52]:
myArray = array2[4:9]

In [53]:
myArray[:] = 700

In [54]:
myArray

array([700, 700, 700, 700, 700])

In [55]:
array2

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

numpy dizilerinde diziler birbirini etkiler

In [56]:
ornekDizi = np.arange(0,24)

In [60]:
ornekDiziKopyasi = ornekDizi.copy()

In [61]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [62]:
ornekDiziKopyaSlicing = ornekDiziKopyasi[3:6]

In [63]:
ornekDiziKopyaSlicing[:] = 800

In [64]:
ornekDiziKopyaSlicing

array([800, 800, 800])

In [65]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [66]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

örnek dizi etkilenmedi. orijinal dizi değişmedi.

## matrix

In [75]:
myList = [[10, 20, 30],[20, 30, 40],[70, 50, 60]]

In [76]:
myMatrixArray = np.array(myList)

In [77]:
myMatrixArray

array([[10, 20, 30],
       [20, 30, 40],
       [70, 50, 60]])

In [78]:
myMatrixArray[0]

array([10, 20, 30])

In [79]:
myMatrixArray[1][2]

40

In [80]:
myMatrixArray[1,2]

40

In [81]:
myMatrixArray[1:,2]

array([40, 60])

In [84]:
newList = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [85]:
newMatrix = np.array(newList)

In [86]:
newMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [88]:
newMatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## operations

In [89]:
yeniBirDizi = np.random.randint(1, 100, 20)

In [90]:
yeniBirDizi

array([54, 13, 93,  9, 26, 58, 96, 54,  1, 78, 95, 92, 88, 66, 77, 44, 62,
       15, 79, 94])

In [94]:
sonucDizisi = yeniBirDizi > 40

In [95]:
yeniBirDizi[sonucDizisi]

array([54, 93, 58, 96, 54, 78, 95, 92, 88, 66, 77, 44, 62, 79, 94])

In [97]:
yeniBirDizi[yeniBirDizi > 24]

array([54, 93, 26, 58, 96, 54, 78, 95, 92, 88, 66, 77, 44, 62, 79, 94])

In [98]:
sonDizi = np.arange(0, 24)

In [99]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [100]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [101]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [103]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

bölümde 0. index 0/0 dan nan olur. Devamını yapar ancak hata da verir.

In [104]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [105]:
np.max(sonDizi)

23