In [1]:
import numpy as np 


## numpy array 


In [2]:
myList = [20, 30, 49]

In [3]:
type(myList)

list

In [4]:
np.array(myList)

array([20, 30, 49])

In [7]:
type(np.array(myList))

numpy.ndarray

In [8]:
matrixList = [[10, 20, 30], [20, 30, 40], [30, 40, 50]]

In [9]:
matrixList[1][0]

20

In [10]:
np.array(matrixList)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [11]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

## zeros

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

## ones

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## linspace

In [18]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

0'dan 20 ye 5 eşit aralığa böl. stop index dahil

In [21]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## eye

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random


In [25]:
np.random.randn(4)

array([ 0.12985919, -1.24834878,  1.10625559,  1.39217002])

In [26]:
np.random.randn(4,4)

array([[-1.04115389, -0.88459218,  0.2943614 , -1.14699482],
       [-1.47223424, -2.17181553, -0.06364452,  0.31292765],
       [-0.17791031, -0.50368129, -1.63449829,  2.13720398],
       [ 1.61141059,  0.81657351, -1.09779877, -1.68428349]])

10 dahil değil

In [34]:
np.random.randint(1, 300, 5)

array([251, 257, 130, 116,  97])

In [35]:
myNumpyArray = np.arange(30)

In [36]:
myNumpyArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

 ## numpy array methods

In [39]:
myNumpyArray.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [40]:
myNumpyArray.max()

29

In [41]:
myNumpyArray.min()

0

In [43]:
myNumpyArray.argmax()

29

kaçıncı indexte

In [44]:
myNumpyArray.shape

(30,)